<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="Class" nsURI="http://www.example.org/Class" nsPrefix="Class">
    <eClassifiers xsi:type="ecore:EClass" name="Class">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperation" ordered="false"
          unique="true" lowerBound="0" upperBound="-1" eType="#/0/Operation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Operation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Dependency">
      <eStructuralFeatures xsi:type="ecore:EReference" name="client" ordered="false"
          unique="false" lowerBound="1" eType="#/0/Operation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="supplier" ordered="false"
          unique="false" lowerBound="1" eType="#/0/Operation"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
