[options]
python_requires = >=3.6
package_dir =
    = src
packages=find:
include_package_data = True
install_requires =
    robotframework>=3.2
    pyparsing==2.4.7
    argparse
    allpairspy

[options.packages.find]
where=src

[options.entry_points]
console_scripts =
     machine = machine.runner:main
