"""Add trip status field

Revision ID: bc173272d969
Revises: 6ebe32e5abcb
Create Date: 2025-06-27 19:43:32.069665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc173272d969'
down_revision: Union[str, None] = '6ebe32e5abcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add status column to trips table
    op.add_column('trips', sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CANCELED', name='tripstatus'), nullable=False, server_default='DRAFT'))
    
    # Update feedback table using batch operations for SQLite compatibility
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.String(), nullable=False))
        batch_op.drop_constraint('feedback_trip_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'activities', ['activity_id'], ['id'])
        batch_op.drop_column('trip_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove status column from trips table
    op.drop_column('trips', 'status')
    
    # Revert feedback table changes using batch operations
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_id', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'trips', ['trip_id'], ['id'])
        batch_op.drop_column('activity_id')
    # ### end Alembic commands ###
